// packages/embeddings/test/parity.test.ts
//
// Embedding retrieval-parity gate (docs/PLAN.md — Spike B).
//
// Loads the FROZEN golden fixture at test/fixtures/bge-golden.json — Python
// sentence-transformers BAAI/bge-base-en-v1.5 vectors, CLS-pooled and
// L2-normalized — and asserts that the TypeScript Transformers.js embedder
// reproduces them with cosine similarity >= 0.999 for EVERY document and EVERY
// query. The fixture is the oracle; it is read-only and must never be
// regenerated by this test.
//
// Config under test (validated Spike B — measured cosine 1.000000):
//   - model    'Xenova/bge-base-en-v1.5'
//   - pooling  'cls'
//   - normalize true (L2)
//   - BGE query prefix 'Represent this sentence for searching relevant passages: '
//     applied to QUERIES ONLY (never to documents)
//   - 768-dim Float32Array per text, input order preserved
//
// Because the golden query vectors were produced WITH the prefix and the golden
// doc vectors WITHOUT it, this single gate also pins the "prefix-on-queries-only"
// rule: dropping the prefix (or applying it to documents) collapses cosine below
// the 0.999 threshold.
//
// NETWORK: the first run downloads the ONNX model weights from the HF Hub. CI
// has outbound network (the model is fetched on demand); vitest.config.ts raises
// the test/hook timeouts to 120s to cover the cold-cache download.
//
// TDD: this FAILS today — packages/embeddings/src/index.ts exports only the
// PACKAGE_NAME placeholder, so `BgeEmbedder` does not exist. It PASSES once the
// embedder is implemented to the validated config above.

import { readFileSync } from 'node:fs';

import { beforeAll, describe, expect, it } from 'vitest';

import { BgeEmbedder } from '../src/index.js';

interface GoldenFixture {
  source: string;
  model: string;
  ts_model: string;
  config: { pooling: string; normalize: boolean; query_prefix: string };
  dim: number;
  docs: string[];
  queries: string[];
  doc_emb: number[][];
  query_emb: number[][];
}

const PARITY_THRESHOLD = 0.999;
const DIM = 768;

const golden = JSON.parse(
  readFileSync(new URL('./fixtures/bge-golden.json', import.meta.url), 'utf8'),
) as GoldenFixture;

// Guarded cosine similarity. The golden and TS vectors are both unit-norm, so
// this reduces to a dot product — but dividing by the norms keeps the assertion
// robust if either side is ever slightly off unit length.
function cosine(a: Float32Array | number[], b: Float32Array | number[]): number {
  if (a.length !== b.length) {
    throw new Error(`dimension mismatch: ${a.length} vs ${b.length}`);
  }
  let dot = 0;
  let normA = 0;
  let normB = 0;
  for (let i = 0; i < a.length; i++) {
    dot += a[i] * b[i];
    normA += a[i] * a[i];
    normB += b[i] * b[i];
  }
  const denom = Math.sqrt(normA) * Math.sqrt(normB);
  return denom === 0 ? 0 : dot / denom;
}

describe('@kgpacks/embeddings — BGE retrieval-parity gate (Spike B golden vectors)', () => {
  let embedder: BgeEmbedder;
  let docVecs: Float32Array[];
  let queryVecs: Float32Array[];

  // One embedder instance, reused across docs and queries: also proves the
  // lazily-loaded pipeline is constructed once and shared (load-once contract).
  beforeAll(async () => {
    embedder = new BgeEmbedder();
    docVecs = await embedder.generate(golden.docs);
    queryVecs = await embedder.generateQuery(golden.queries);
  });

  it('uses the frozen 768-dim Spike B fixture as its oracle', () => {
    expect(golden.dim).toBe(DIM);
    expect(golden.config.pooling).toBe('cls');
    expect(golden.config.normalize).toBe(true);
    expect(golden.ts_model).toBe('Xenova/bge-base-en-v1.5');
    expect(golden.docs).toHaveLength(golden.doc_emb.length);
    expect(golden.queries).toHaveLength(golden.query_emb.length);
    expect(golden.doc_emb[0]).toHaveLength(DIM);
    expect(golden.query_emb[0]).toHaveLength(DIM);
  });

  it('returns one 768-dim Float32Array per document, order preserved', () => {
    expect(docVecs).toHaveLength(golden.docs.length);
    for (const v of docVecs) {
      expect(v).toBeInstanceOf(Float32Array);
      expect(v).toHaveLength(DIM);
    }
  });

  it('returns one 768-dim Float32Array per query, order preserved', () => {
    expect(queryVecs).toHaveLength(golden.queries.length);
    for (const v of queryVecs) {
      expect(v).toBeInstanceOf(Float32Array);
      expect(v).toHaveLength(DIM);
    }
  });

  it('every DOCUMENT vector matches the golden vector (cosine >= 0.999)', () => {
    golden.docs.forEach((doc, i) => {
      const sim = cosine(docVecs[i], golden.doc_emb[i]);
      expect(sim, `doc[${i}] "${doc}" cosine=${sim}`).toBeGreaterThanOrEqual(PARITY_THRESHOLD);
    });
  });

  it('every QUERY vector matches the golden vector (cosine >= 0.999)', () => {
    golden.queries.forEach((q, i) => {
      const sim = cosine(queryVecs[i], golden.query_emb[i]);
      expect(sim, `query[${i}] "${q}" cosine=${sim}`).toBeGreaterThanOrEqual(PARITY_THRESHOLD);
    });
  });

  it('output vectors are unit-norm (L2-normalized)', () => {
    for (const v of [...docVecs, ...queryVecs]) {
      let norm = 0;
      for (const x of v) norm += x * x;
      expect(Math.sqrt(norm)).toBeCloseTo(1, 3);
    }
  });

  it('applies the BGE prefix to QUERIES ONLY (same text embeds differently as doc vs query)', async () => {
    const text = golden.queries[0];
    const asDoc = (await embedder.generate([text]))[0];
    const asQuery = (await embedder.generateQuery([text]))[0];

    // The prefix meaningfully changes the embedding, so the same string embedded
    // as a document differs from the same string embedded as a query...
    expect(cosine(asDoc, asQuery)).toBeLessThan(PARITY_THRESHOLD);
    // ...and the prefixed (query) form is the one that matches the golden query.
    expect(cosine(asQuery, golden.query_emb[0])).toBeGreaterThanOrEqual(PARITY_THRESHOLD);
  });
});
